"""
Render a tool's usage instructions (Markdown) to PDF via WeasyPrint.
WeasyPrint is optional — if unavailable, this module logs a warning and
returns None so deployment keeps succeeding.

Public API:
    generate_pdf(tool_id, markdown_content) -> str | None
"""
from __future__ import annotations

import logging
import re
from html import escape
from pathlib import Path
from typing import Optional

log = logging.getLogger("forge.pdf")

_REPO_ROOT = Path(__file__).resolve().parent.parent
INSTRUCTIONS_DIR = _REPO_ROOT / "static" / "instructions"

CSS = """
@page { size: Letter; margin: 0.75in; }
body {
    font-family: "DM Sans", "Helvetica Neue", Arial, sans-serif;
    color: #111;
    font-size: 11pt;
    line-height: 1.5;
}
header.forge-header {
    border-bottom: 2px solid #0066FF;
    padding-bottom: 8px;
    margin-bottom: 18px;
    font-family: "DM Mono", "Menlo", monospace;
    font-size: 10pt;
    letter-spacing: 2px;
    color: #0066FF;
    text-transform: uppercase;
}
footer.forge-footer {
    border-top: 1px solid #ccc;
    padding-top: 8px;
    margin-top: 28px;
    font-size: 8.5pt;
    color: #666;
    text-align: center;
}
h1 { font-size: 22pt; margin: 0 0 8px 0; }
h2 { font-size: 14pt; margin-top: 18px; color: #0066FF; }
h3 { font-size: 12pt; margin-top: 14px; }
code {
    background: #f4f4f6;
    padding: 1px 4px;
    border-radius: 3px;
    font-family: "DM Mono", monospace;
    font-size: 10pt;
}
pre {
    background: #f4f4f6;
    padding: 10px;
    border-radius: 4px;
    overflow-x: auto;
}
ul, ol { margin-left: 18px; }
strong { color: #111; }
"""


def _markdown_to_html(md: str) -> str:
    """
    Tiny Markdown → HTML converter. Enough for the auto-generated
    instructions format we produce; keeps us free of an extra dep.
    """
    lines = md.splitlines()
    html_parts = []
    in_list = False
    in_ordered = False
    in_code = False
    code_buf = []

    def close_list():
        nonlocal in_list, in_ordered
        if in_list:
            html_parts.append("</ul>")
            in_list = False
        if in_ordered:
            html_parts.append("</ol>")
            in_ordered = False

    def inline(text: str) -> str:
        text = escape(text)
        text = re.sub(
            r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text
        )
        text = re.sub(r"_([^_]+)_", r"<em>\1</em>", text)
        text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
        text = re.sub(
            r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text
        )
        return text

    for raw in lines:
        line = raw.rstrip()
        if line.startswith("```"):
            if in_code:
                html_parts.append(
                    "<pre><code>" + escape("\n".join(code_buf)) + "</code></pre>"
                )
                code_buf = []
                in_code = False
            else:
                close_list()
                in_code = True
            continue
        if in_code:
            code_buf.append(line)
            continue
        if not line.strip():
            close_list()
            continue
        m_h = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m_h:
            close_list()
            level = len(m_h.group(1))
            html_parts.append(f"<h{level}>{inline(m_h.group(2))}</h{level}>")
            continue
        m_ul = re.match(r"^[-*]\s+(.*)$", line)
        if m_ul:
            if in_ordered:
                html_parts.append("</ol>")
                in_ordered = False
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{inline(m_ul.group(1))}</li>")
            continue
        m_ol = re.match(r"^\d+\.\s+(.*)$", line)
        if m_ol:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            if not in_ordered:
                html_parts.append("<ol>")
                in_ordered = True
            html_parts.append(f"<li>{inline(m_ol.group(1))}</li>")
            continue
        close_list()
        html_parts.append(f"<p>{inline(line)}</p>")

    if in_code and code_buf:
        html_parts.append(
            "<pre><code>" + escape("\n".join(code_buf)) + "</code></pre>"
        )
    close_list()
    return "\n".join(html_parts)


def _wrap_html(body_html: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Forge — Usage Guide</title>
  <style>{CSS}</style>
</head>
<body>
  <header class="forge-header">FORGE &middot; Internal AI Tool Platform</header>
  {body_html}
  <footer class="forge-footer">
    Generated by Forge. Questions? #forge-help on Slack.
  </footer>
</body>
</html>"""


def generate_pdf(tool_id: int, markdown_content: str) -> Optional[str]:
    """
    Render the given Markdown to a PDF at static/instructions/{tool_id}.pdf.
    Returns the absolute path on success; returns None if WeasyPrint is
    not installed or rendering fails.
    """
    try:
        import weasyprint  # type: ignore
    except ImportError:
        log.warning("WeasyPrint not installed — skipping PDF generation")
        return None
    except Exception as exc:
        log.warning("WeasyPrint import failed: %s — skipping PDF", exc)
        return None

    try:
        body_html = _markdown_to_html(markdown_content)
        full_html = _wrap_html(body_html)
        INSTRUCTIONS_DIR.mkdir(parents=True, exist_ok=True)
        out_path = INSTRUCTIONS_DIR / f"{tool_id}.pdf"
        weasyprint.HTML(string=full_html).write_pdf(str(out_path))
        return str(out_path)
    except Exception as exc:
        log.warning("PDF render failed for tool %s: %s", tool_id, exc)
        return None
