"""
Forge project scaffolder — creates a new Claude Code project directory
with governance skills baked into CLAUDE.md.

The generated files are HUMAN-READABLE. Section headers, inline comments
explaining why each section exists. A new user should be able to read the
generated CLAUDE.md top to bottom and understand what the scaffolding is
doing for them.
"""

import hashlib
import json
import os
import time
from typing import Any


def scaffold_project(
    slug: str,
    description: str,
    skills: list[dict],
    user_id: str,
    user_email: str = "",
) -> dict:
    """
    Create a new Claude Code project directory with governance scaffolding.

    Returns:
        {"path": str, "files": list[str], "checksum": str}
    """
    # Resolve project directory
    base_dir = os.environ.get("FORGE_PROJECTS_DIR",
                              os.path.expanduser("~/forge-projects"))
    project_dir = os.path.join(base_dir, slug)

    if os.path.exists(project_dir):
        raise FileExistsError(f"Directory already exists: {project_dir}")

    os.makedirs(project_dir, exist_ok=True)
    os.makedirs(os.path.join(project_dir, ".forge"), exist_ok=True)

    files_created = []

    # 1. Generate CLAUDE.md
    claude_md = _generate_claude_md(slug, description, skills)
    _write(project_dir, "CLAUDE.md", claude_md)
    files_created.append("CLAUDE.md")

    # 2. Generate .forge/manifest.json
    checksum = _compute_governance_checksum(skills, claude_md)
    manifest = {
        "forge_version": "1.0",
        "project_slug": slug,
        "description": description,
        "skills_applied": [s["slug"] for s in skills],
        "governance_checksum": checksum,
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "created_by": user_email or user_id,
    }
    _write(project_dir, ".forge/manifest.json", json.dumps(manifest, indent=2))
    files_created.append(".forge/manifest.json")

    # 3. Generate .forge/submission-config.json (empty — populated on submit)
    _write(project_dir, ".forge/submission-config.json", json.dumps({
        "submitted": False,
        "submission_id": None,
    }, indent=2))
    files_created.append(".forge/submission-config.json")

    # 4. Generate README.md
    readme = _generate_readme(slug, description, skills)
    _write(project_dir, "README.md", readme)
    files_created.append("README.md")

    # 5. Generate .gitignore
    gitignore = _generate_gitignore()
    _write(project_dir, ".gitignore", gitignore)
    files_created.append(".gitignore")

    return {
        "path": project_dir,
        "files": files_created,
        "checksum": checksum,
    }


def _generate_claude_md(slug: str, description: str, skills: list[dict]) -> str:
    """Generate a human-readable CLAUDE.md with governance skills baked in."""
    lines = []

    lines.append(f"# {slug}")
    lines.append("")
    if description:
        lines.append(f"> {description}")
        lines.append("")
    lines.append("<!-- This file was generated by Forge. It configures Claude Code")
    lines.append("     to follow your company's governance rules and best practices.")
    lines.append("     You can (and should!) add your own sections below the governance")
    lines.append("     sections. Just don't delete the required sections marked with -->")
    lines.append("<!--     [REQUIRED BY FORGE] — they're checked on submission. -->")
    lines.append("")

    # Project context section
    lines.append("## Project Context")
    lines.append("")
    lines.append("<!-- Add your project-specific instructions here. What does this tool do?")
    lines.append("     What APIs does it talk to? What data does it handle? The more context")
    lines.append("     you give Claude, the better it performs. -->")
    lines.append("")
    lines.append(f"This is a Claude Code project called **{slug}**.")
    if description:
        lines.append(f"Purpose: {description}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Governance skills
    if skills:
        lines.append("## Governance & Company Standards")
        lines.append("")
        lines.append("<!-- The sections below encode your company's governance rules.")
        lines.append("     They were selected when this project was created in Forge.")
        lines.append("     Each section marked [REQUIRED BY FORGE] must be present when")
        lines.append("     you submit this project for review. You can edit the content")
        lines.append("     but don't delete the section headers. -->")
        lines.append("")

        for skill in skills:
            content = skill.get("content", "")
            if content:
                # Add a marker so the validator knows this is a required section
                lines.append(f"<!-- [REQUIRED BY FORGE] Skill: {skill['slug']} -->")
                lines.append("")
                lines.append(content)
                lines.append("")
                lines.append("---")
                lines.append("")

    # Your additions section
    lines.append("## Your Additions")
    lines.append("")
    lines.append("<!-- Everything below this line is yours. Add project-specific rules,")
    lines.append("     examples, context, or instructions. Claude reads the entire file")
    lines.append("     at the start of every session. -->")
    lines.append("")

    return "\n".join(lines)


def _generate_readme(slug: str, description: str, skills: list[dict]) -> str:
    """Generate a quick-start README."""
    skill_names = ", ".join(s["title"] for s in skills) if skills else "none"

    return f"""# {slug}

{description or "A Claude Code project scaffolded by Forge."}

## Quick Start

1. Open this directory in your terminal
2. Run `claude` to start Claude Code
3. Start building — the governance rules in CLAUDE.md are already loaded

## Governance Skills Applied

{skill_names}

These skills are baked into CLAUDE.md and will be validated when you submit
this project to Forge for review.

## Submitting for Review

When your tool is ready, run:

```bash
cd {os.path.expanduser(f"~/forge-projects/{slug}")}
python3 ~/projects/forge/cli/forge_submit.py
```

This packages your project and submits it to Forge's governance pipeline.

## Files

- `CLAUDE.md` — Claude Code configuration with governance rules
- `.forge/manifest.json` — project metadata and governance checksums
- `README.md` — this file
- `.gitignore` — standard ignores
"""


def _generate_gitignore() -> str:
    return """# Dependencies
node_modules/
venv/
.venv/
__pycache__/
*.pyc

# Environment
.env
.env.local

# Build
dist/
build/
*.egg-info/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Forge internals (keep .forge/ tracked)
!.forge/
"""


def _compute_governance_checksum(skills: list[dict], claude_md: str) -> str:
    """Compute a checksum of the required governance sections.

    This checksum is over the REQUIRED SECTIONS content, not the whole file.
    Users can add/edit other sections freely without invalidating the checksum.
    """
    hasher = hashlib.sha256()
    for skill in skills:
        required = skill.get("required_sections", "[]")
        if isinstance(required, str):
            required = json.loads(required)
        for section_header in required:
            # Find the section in claude_md and hash its content
            content = _extract_section_content(claude_md, section_header)
            if content:
                hasher.update(content.encode("utf-8"))
    return hasher.hexdigest()[:16]


def _extract_section_content(md: str, header: str) -> str:
    """Extract content under a markdown header until the next same-level header."""
    lines = md.split("\n")
    header_clean = header.strip().lstrip("#").strip()
    level = header.count("#")
    if level == 0:
        level = 2  # default to h2

    capturing = False
    content_lines = []

    for line in lines:
        if line.startswith("#" * level + " "):
            line_clean = line.lstrip("#").strip()
            if line_clean == header_clean:
                capturing = True
                continue
            elif capturing:
                break  # hit next same-level header
        if capturing:
            content_lines.append(line)

    return "\n".join(content_lines).strip()


def _write(project_dir: str, rel_path: str, content: str):
    """Write a file, creating parent directories as needed."""
    full = os.path.join(project_dir, rel_path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)
